# config.py

# Robot Control Modes
CTRL_MODE_STANDBY = 0x00
CTRL_MODE_CAN = 0x01

# Move Modes
MOVE_MODE_POSE = 0x00
MOVE_MODE_JOINT = 0x01
MOVE_MODE_LINEAR = 0x02

# Gripper Codes
GRIPPER_ENABLE = 0x01
GRIPPER_DISABLE = 0x02
GRIPPER_CLEAR_ERR = 0x03

# Defaults
DEFAULT_SPEED = 50
DEFAULT_GRIPPER_EFFORT = 1000

# Connection
CAN_INTERFACE = "can0"
HEARTBEAT_RATE = 50  # Hz
HEARTBEAT_INTERVAL = 1.0 / HEARTBEAT_RATE
